config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: [:create, :new]
  resource :identity, only: [:create, :new]
  delete 'log_out' => 'sessions#destroy', as: :log_out
  get 'log_in' => 'sessions#new', as: :log_in
  get 'sign_up' => 'identities#new', as: :sign_up
  resources :images, only: [:index, :new, :create], path: '/imagenes'
  root to: 'images#index'
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  has_secure_password validations: true

  validates :email, presence: true, uniqueness: true
  validates :password_confirmation, presence: true, if: -> r { r.password.present? }

  has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :photo, PhotoUploader

	belongs_to :identity
	
	enum category: %w(portrait landscape city\ exploration nature animals)

	validates :name, presence: true

	def tags_text
		return if self.tags.nil?
    self.tags.join(', ')
  end

  def tags_text=(value)
    self.tags = value.split(',').map{ |tag| tag.strip }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_identity, :identity_signed_in?, :warden_message

protected
  def current_identity
    warden.user(scope: :identity)
  end

  def identity_signed_in?
    warden.authenticate?(scope: :identity)
  end

  def authenticate!
    redirect_to root_path, notice: t('.not_logged') unless identity_signed_in?
  end

  def warden_message
    warden.message
  end

  def warden
    request.env['warden']
  end

end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController

  def new
    @identity = Identity.new
  end

  def create
    @identity = Identity.new identity_params

    if @identity.save
      warden.set_user(@identity, scope: :identity)
      redirect_to root_url, notice: t('.sign_up')
    else
      render :new
    end
  end

private
  def identity_params
    params.require(:identity).permit :email, :password, :password_confirmation
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :authenticate!, only: [:new, :create]
	def index
		@images = Image.all 
	end

	def new
		@image = Image.new
	end

	def create
		@image = Image.new secure_params
		@image.identity = current_identity
		
		if @image.save
			return redirect_to images_path, notice: t('.created', 
				model: @image.class.model_name.human)
		end

		render :new
	end

	private
	def secure_params
		params.require(:image).permit :name, :description, :category, :tags_text, 
		:photo
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @identity = Identity.new
  end

  def create
    warden.authenticate!(scope: :identity)
    redirect_to root_url, notice: t('.logged_in')
  end

  def destroy
    warden.logout(:identity)
    redirect_to root_url, notice: t('.logged_out')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def image_categories
		Image.categories.inject({}) do |hash, elem|
			hash.merge!(t("categories.#{elem.first.gsub(' ', '_')}") => elem.first)
		end
	end
end

app/views/identities/new.html.erb
<%= form_for @identity, url: identity_path do |form| %>
  <% if @identity.errors.any? %>
    <h2>Form is invalid</h2>
    <ul>
      <% for message in @identity.errors.full_messages %>
        <li><%= message %>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </p>
  <p>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </p>
  <p class='button'><%= form.submit t('.create')%></p>
<% end %>

app/views/images/_image.html.erb
<div class="image-box">
	<div class="image-content">
		<%= image_tag image.photo.thumb.url %>
		<h2><%= image.name %> <span><%= image.try(:identity).try(:email) %></span></h2>
	</div>
</div>

app/views/images/index.html.erb
<h1><%= t('.title') %></h1>

<%- if identity_signed_in? %>
	<p>
		<%= link_to t('.new_link'), new_image_path %>
	</p>
<% end %>

<div class="images">
	<%= render @images %>
</div>

app/views/images/new.html.erb
<% model_name = @image.class.model_name.human %>
<h1><%= t('.title', model: model_name) %></h1>

<%= form_for @image, html: {class: 'pure-form pure-form-aligned'}, builder: CustomFormBuilder do |form| %>
	<%= form.form_error %>
	
	<div class="pure-control-group">
		<%= form.label :name %>
		<%= form.text_field :name %>
		<%= form.field_error :name %>
	</div>
	<div class="pure-control-group">
		<%= form.label :description %>
		<%= form.text_area :description %>
	</div>
	<div class="pure-control-group">
		<%= form.label :category %>
		<%= form.collection_select :category, image_categories, :last, :first %>
	</div>
	<div class='pure-control-group'>
    <%= form.label :tags_text %>
    <%= form.text_field :tags_text %>
  </div>
  <div class='pure-control-group'>
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>
	<div class="pure-control">
		<%= form.submit class: 'pure-button pure-button-primary' %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onepx</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="user">
		<%- if identity_signed_in? %>
			<span>Hola! <%= current_identity.email %></span>
			<%= link_to 'Cerrar sesion', log_out_path, method: :delete %>
		<% else %>
			<%= link_to 'Iniciar sesion', log_in_path %>
			<%= link_to 'Crear cuenta', sign_up_path %>
		<% end %>
	</div>
	<div id="flash">
		<% flash.each do |key, value| %>
			<div id="flash-<%= key %>"><%= value %></div>
		<% end %>
	</div>
	<%= yield %>

</body>
</html>